path = File.expand_path('../', __FILE__)
require File.join(path, 'lib/client.rb')
require File.join(path, 'lib/dialogue.rb')
require File.join(path, 'lib/knowledgeQA.rb')
require File.join(path, 'lib/imageRecognition.rb')
require File.join(path, 'lib/sentenceUnderstanding.rb')
require File.join(path, 'lib/gooLanguageAnalysis.rb')
require File.join(path, 'lib/webCuration.rb')
require File.join(path, 'lib/characterRecognition.rb')
require File.join(path, 'lib/textToSpeech.rb')