require "mocodo/version"
require "mocodo/base"
require "mocodo/dialogue"
require "mocodo/knowledge_qa"
require 'mocodo/text_to_speech'
require 'mocodo/image_recognition'
require 'mocodo/scenario_dialogue'
require 'mocodo/sentence_understanding'
require 'mocodo/web_curation'
require 'mocodo/goo_language_analysis'
require 'mocodo/mountain_identification'
require 'mocodo/character_recognition'